const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Plugins.TiledBg,
		C3.Behaviors.solid,
		C3.Plugins.Tilemap,
		C3.Plugins.SpeechSynthesis,
		C3.Behaviors.Timer,
		C3.Plugins.Audio,
		C3.Plugins.Keyboard,
		C3.Plugins.Text,
		C3.Plugins.Spritefont2,
		C3.Plugins.Mouse,
		C3.Behaviors.custom,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Cnds.IsOutsideLayout,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.SpeechSynthesis.Acts.SpeakText,
		C3.Behaviors.custom.Acts.SetSpeed,
		C3.Behaviors.custom.Acts.SetAngleOfMotion,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Acts.SetVectorX,
		C3.Plugins.Audio.Cnds.IsAnyPlaying,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Text.Acts.AppendText,
		C3.Plugins.System.Acts.RestartLayout
	];
};
self.C3_JsPropNameTable = [
	{isDead: 0},
	{isWin: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Player: 0},
	{TiledBackground2: 0},
	{Solid: 0},
	{Tilemap: 0},
	{SpeechSynthesis: 0},
	{Timer: 0},
	{Apple: 0},
	{Audio: 0},
	{Keyboard: 0},
	{Score: 0},
	{TiledBackground: 0},
	{Title: 0},
	{ControlsText: 0},
	{ControlsText2: 0},
	{PlayBtn: 0},
	{Player2: 0},
	{Mouse: 0},
	{Custom: 0},
	{Sprite: 0},
	{ToRight: 0},
	{ToLeft: 0},
	{Finish: 0},
	{TiledBackground3: 0},
	{Win: 0},
	{Trphy: 0},
	{EndScore: 0},
	{ByAhmadFakhrulBawani: 0},
	{SawTrap: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{GameOverTxt: 0},
	{ResetBtn: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Platform: class extends self.ISpriteInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	SpeechSynthesis: class extends self.IInstance {},
	Timer: class extends self.ISpriteInstance {},
	Apple: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Score: class extends self.ITextInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Title: class extends self.ISpriteFontInstance {},
	ControlsText: class extends self.ITextInstance {},
	ControlsText2: class extends self.ITextInstance {},
	PlayBtn: class extends self.ISpriteInstance {},
	Player2: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite: class extends self.ISpriteInstance {},
	ToRight: class extends self.ISpriteInstance {},
	ToLeft: class extends self.ISpriteInstance {},
	Finish: class extends self.ISpriteInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	Win: class extends self.ITextInstance {},
	Trphy: class extends self.ISpriteInstance {},
	EndScore: class extends self.ITextInstance {},
	ByAhmadFakhrulBawani: class extends self.ITextInstance {},
	SawTrap: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	GameOverTxt: class extends self.ITextInstance {},
	ResetBtn: class extends self.ISpriteInstance {}
}