const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
  return [
    C3.Plugins.Sprite,
    C3.Behaviors.Platform,
    C3.Behaviors.scrollto,
    C3.Plugins.TiledBg,
    C3.Behaviors.solid,
    C3.Plugins.Tilemap,
    C3.Plugins.SpeechSynthesis,
    C3.Behaviors.Timer,
    C3.Plugins.Audio,
    C3.Plugins.Keyboard,
    C3.Plugins.Text,
    C3.Plugins.Spritefont2,
    C3.Plugins.Sprite.Cnds.IsOutsideLayout,
    C3.Plugins.Sprite.Acts.Destroy,
    C3.Behaviors.Timer.Acts.StartTimer,
    C3.Plugins.Audio.Acts.Play,
    C3.Plugins.System.Cnds.OnLayoutStart,
    C3.Plugins.SpeechSynthesis.Acts.SpeakText,
    C3.Plugins.System.Acts.SetVar,
    C3.Behaviors.Timer.Cnds.OnTimer,
    C3.Plugins.System.Acts.RestartLayout,
    C3.Plugins.Sprite.Cnds.OnCollision,
    C3.Plugins.System.Acts.AddVar,
    C3.Plugins.Text.Acts.SetText,
    C3.Plugins.Text.Acts.AppendText,
    C3.Plugins.Keyboard.Cnds.OnKey,
    C3.Behaviors.Platform.Acts.SimulateControl,
    C3.Behaviors.Platform.Cnds.IsOnFloor,
    C3.Plugins.Keyboard.Cnds.IsKeyDown,
    C3.Plugins.Sprite.Acts.SetAnim,
    C3.Behaviors.Platform.Acts.SetVectorX,
    C3.Plugins.Audio.Cnds.IsAnyPlaying,
    C3.Plugins.Keyboard.Cnds.OnKeyReleased,
  ];
};
self.C3_JsPropNameTable = [
  { Platform: 0 },
  { ScrollTo: 0 },
  { Player: 0 },
  { TiledBackground2: 0 },
  { Solid: 0 },
  { Tilemap: 0 },
  { SpeechSynthesis: 0 },
  { Timer: 0 },
  { Apple: 0 },
  { Audio: 0 },
  { Keyboard: 0 },
  { Score: 0 },
  { TiledBackground: 0 },
  { Title: 0 },
  { ControlsText: 0 },
  { ControlsText2: 0 },
  { Text: 0 },
  { Sprite: 0 },
  { Sprite2: 0 },
  { Player2: 0 },
];

self.InstanceType = {
  Player: class extends self.ISpriteInstance {},
  TiledBackground2: class extends self.ITiledBackgroundInstance {},
  Platform: class extends self.ISpriteInstance {},
  Tilemap: class extends self.ITilemapInstance {},
  SpeechSynthesis: class extends self.IInstance {},
  Timer: class extends self.ISpriteInstance {},
  Apple: class extends self.ISpriteInstance {},
  Audio: class extends self.IInstance {},
  Keyboard: class extends self.IInstance {},
  Score: class extends self.ITextInstance {},
  TiledBackground: class extends self.ITiledBackgroundInstance {},
  Title: class extends self.ISpriteFontInstance {},
  ControlsText: class extends self.ITextInstance {},
  ControlsText2: class extends self.ITextInstance {},
  Text: class extends self.ITextInstance {},
  Sprite: class extends self.ISpriteInstance {},
  Sprite2: class extends self.ISpriteInstance {},
  Player2: class extends self.ISpriteInstance {},
};
